import React, { useState, useEffect } from 'react';
import { 
  SparklesIcon, 
  ChartBarIcon, 
  ExclamationTriangleIcon, 
  CheckBadgeIcon, 
  ArrowPathIcon,
  LightBulbIcon
} from '@heroicons/react/24/outline';

const AITutor = () => {
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState(null);

  // Mock initial report data
  const initialReport = {
    overallScore: 78,
    status: 'Progressing Well',
    summary: "You've shown strong consistency in Array and String problems. However, your performance in Dynamic Programming suggests a need for more focused practice on foundational recurrence relations.",
    strengths: ['Array Manipulation', 'Two Pointers'],
    weaknesses: ['Dynamic Programming (Memoization)', 'Graph Traversals'],
    recommendations: [
      { topic: 'Climbing Stairs (DP)', type: 'Practice' },
      { topic: 'Graph BFS/DFS Visualization', type: 'Review' },
      { topic: 'Mock Interview: Arrays', type: 'Assess' }
    ]
  };

  useEffect(() => {
     // Simulate loading initial data
     setReport(initialReport);
  }, []);

  const generateNewReport = () => {
    setLoading(true);
    // Simulate AI Generation delay
    setTimeout(() => {
      setLoading(false);
      // Just refreshing the same data for demo, typically this would fetch new analysis
      setReport({
        ...initialReport,
        overallScore: Math.floor(Math.random() * (85 - 75 + 1)) + 75, // Randomize slightly
        status: 'Updated Analysis'
      });
    }, 2000);
  };

  return (
    <div className="min-h-screen bg-black text-white p-8 font-sans space-y-8 animate-fade-in">
      {/* Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold text-white tracking-tight flex items-center gap-2">
            AI Performance Report
            <SparklesIcon className="w-6 h-6 text-orange-500" />
          </h1>
          <p className="text-gray-400 mt-1">Personalized analysis of your learning journey generated by our AI.</p>
        </div>
        
        <button 
          onClick={generateNewReport}
          disabled={loading}
          className="flex items-center gap-2 bg-[#1a1a1a] border border-[#333] hover:border-orange-500 hover:text-orange-500 text-white px-4 py-2 rounded-lg transition-all disabled:opacity-50"
        >
          {loading ? (
             <ArrowPathIcon className="w-5 h-5 animate-spin" />
          ) : (
             <SparklesIcon className="w-5 h-5" />
          )}
          <span>{loading ? 'Analyzing...' : 'Refresh Analysis'}</span>
        </button>
      </div>

      {report && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Main Analysis Card */}
          <div className="lg:col-span-2 space-y-6">
             {/* Summary Section */}
             <div className="bg-[#111] p-6 rounded-2xl border border-[#222]">
                <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
                   <ChartBarIcon className="w-5 h-5 text-blue-500" />
                   Executive Summary
                </h2>
                <p className="text-gray-300 leading-relaxed border-l-4 border-orange-500 pl-4 py-1 italic">
                   "{report.summary}"
                </p>
             </div>

             {/* Strengths & Weaknesses */}
             <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="bg-[#161616] p-5 rounded-xl border border-green-900/30">
                   <h3 className="text-green-400 font-bold mb-3 flex items-center gap-2">
                      <CheckBadgeIcon className="w-5 h-5" />
                      Strengths
                   </h3>
                   <ul className="space-y-2">
                      {report.strengths.map((item, i) => (
                         <li key={i} className="flex items-center gap-2 text-sm text-gray-300">
                            <div className="w-1.5 h-1.5 bg-green-500 rounded-full"></div>
                            {item}
                         </li>
                      ))}
                   </ul>
                </div>

                <div className="bg-[#161616] p-5 rounded-xl border border-red-900/30">
                   <h3 className="text-red-400 font-bold mb-3 flex items-center gap-2">
                      <ExclamationTriangleIcon className="w-5 h-5" />
                      Areas for Improvement
                   </h3>
                   <ul className="space-y-2">
                      {report.weaknesses.map((item, i) => (
                         <li key={i} className="flex items-center gap-2 text-sm text-gray-300">
                            <div className="w-1.5 h-1.5 bg-red-500 rounded-full"></div>
                            {item}
                         </li>
                      ))}
                   </ul>
                </div>
             </div>
             
             {/* AI Recommendations */}
             <div className="bg-gradient-to-r from-[#1a1a1a] to-[#111] p-6 rounded-2xl border border-[#333]"> 
                <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
                   <LightBulbIcon className="w-5 h-5 text-yellow-500" />
                   Recommended Next Steps
                </h2>
                <div className="space-y-3">
                   {report.recommendations.map((rec, i) => (
                      <div key={i} className="flex flex-col sm:flex-row sm:items-center justify-between bg-[#222] p-4 rounded-xl hover:bg-[#2a2a2a] transition-colors cursor-pointer group">
                         <div>
                            <span className="text-xs font-bold text-orange-500 bg-orange-500/10 px-2 py-0.5 rounded uppercase tracking-wide">{rec.type}</span>
                            <h4 className="text-white font-medium mt-1 group-hover:text-orange-400 transition-colors">{rec.topic}</h4>
                         </div>
                         <div className="mt-3 sm:mt-0">
                            <span className="text-gray-500 text-sm flex items-center gap-1 group-hover:translate-x-1 transition-transform">
                               Start 
                               <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-3 h-3">
                                 <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3" />
                               </svg>
                            </span>
                         </div>
                      </div>
                   ))}
                </div>
             </div>
          </div>

          {/* Sidebar Stats */}
          <div className="lg:col-span-1 space-y-6">
             <div className="bg-[#111] rounded-2xl border border-[#222] p-8 flex flex-col items-center justify-center text-center relative overflow-hidden">
                <div className="absolute top-0 w-full h-1 bg-gradient-to-r from-orange-500 via-red-500 to-purple-500"></div>
                <h3 className="text-gray-400 text-sm font-medium uppercase tracking-widest mb-4">Overall Readiness</h3>
                <div className="text-6xl font-bold text-white mb-2">{report.overallScore}%</div>
                <p className="text-orange-500 font-medium">{report.status}</p>
             </div>

             <div className="bg-[#1a1a1a] p-6 rounded-2xl border border-[#333]">
                <h3 className="text-white font-bold mb-4">Performance Metrics</h3>
                <div className="space-y-4">
                   <div>
                      <div className="flex justify-between text-xs mb-1">
                         <span className="text-gray-400">Consistency</span>
                         <span className="text-white">92%</span>
                      </div>
                      <div className="w-full bg-[#333] h-1.5 rounded-full overflow-hidden">
                         <div className="bg-green-500 h-full w-[92%]"></div>
                      </div>
                   </div>
                   <div>
                      <div className="flex justify-between text-xs mb-1">
                         <span className="text-gray-400">Problem Solving Speed</span>
                         <span className="text-white">65%</span>
                      </div>
                      <div className="w-full bg-[#333] h-1.5 rounded-full overflow-hidden">
                         <div className="bg-yellow-500 h-full w-[65%]"></div>
                      </div>
                   </div>
                   <div>
                      <div className="flex justify-between text-xs mb-1">
                         <span className="text-gray-400">Code Quality</span>
                         <span className="text-white">78%</span>
                      </div>
                      <div className="w-full bg-[#333] h-1.5 rounded-full overflow-hidden">
                         <div className="bg-blue-500 h-full w-[78%]"></div>
                      </div>
                   </div>
                </div>
             </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AITutor;
